jobs:
  xcodebuild:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: git submodule update --recursive --init
    
      - run:
          name: Test UIKit for macOS
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "macosx"
              -scheme "UIKit"
              test |
            xcpretty --color --report junit

      - run:
          name: Test iOSTestTarget
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "iphonesimulator"
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8 Plus'
              -scheme "UIKit iOSTestTarget"
              test |
            xcpretty --color --report junit

      - run:
          name: Build demo app for iOS
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "iphonesimulator"
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8 Plus'
              -scheme "DemoApp"
              build |
            xcpretty --color --report junit
          path: ./samples/getting-started


  gradlebuild:
    docker:
      - image: flowkey/androidswift
    steps:
      - checkout
      - run: git submodule update --recursive --init
      - run: cp -f ./swift-android-toolchain/usr/Linux/ld.gold /usr/bin/
      - run:
          name: Build demo app for android
          command: ./gradlew assembleDebug
          path: ./samples/getting-started/android

workflows:
  uikit:
    jobs:
      - xcodebuild
      - gradlebuild
