version: "2.1"
orbs:
    macos: circleci/macos@2.5.2

jobs:
    build:
        macos:
            xcode: "16.1.0"
        steps:
            - macos/install-rosetta
            - checkout
            - run: git submodule update --recursive --init

            - run:
                  name: Test UIKit for macOS
                  command: set -o pipefail &&
                      xcodebuild
                      CODE_SIGNING_REQUIRED=NO
                      CODE_SIGN_IDENTITY=""
                      PROVISIONING_PROFILE=""
                      -sdk "macosx"
                      -arch "x86_64"
                      -scheme "UIKit"
                      build test |
                      xcpretty --color --report junit

            - run:
                  name: Test iOSTestTarget
                  command: set -o pipefail &&
                      xcodebuild
                      CODE_SIGNING_REQUIRED=NO
                      CODE_SIGN_IDENTITY=""
                      PROVISIONING_PROFILE=""
                      -sdk "iphonesimulator"
                      -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16'
                      -scheme "UIKit iOSTestTarget"
                      test |
                      xcpretty --color --report junit

            - run:
                  name: Build demo app for iOS
                  command: set -o pipefail &&
                      xcodebuild
                      CODE_SIGNING_REQUIRED=NO
                      CODE_SIGN_IDENTITY=""
                      PROVISIONING_PROFILE=""
                      -sdk "iphonesimulator"
                      -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16'
                      -scheme "DemoApp"
                      build |
                      xcpretty --color --report junit
                  path: ./samples/getting-started
