version: 2

jobs:
  build:
    macos:
      xcode: "9.3.0"
    
    steps:
      - checkout
      - run: git submodule update --recursive --init
    
      - run:
          name: Test UIKit for macOS
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "macosx"
              -scheme "UIKit"
              test |
            xcpretty --color --report junit

      - run:
          name: Test iOSTestTarget
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "iphonesimulator"
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8 Plus'
              -scheme "iOSTestTarget"
              test |
            xcpretty --color --report junit
