#!/bin/bash
set -e

function die() {
    echo "$1" 1>&2
    exit 1
}

SCRIPT_PATH=`dirname $0`
TEMPLATE_PATH=${SCRIPT_PATH}/demo

[[ $1 == "create" ]] || die "usage: $0 create"


BUNDLE_IDENTIFIER=`grep -m 1 PRODUCT_BUNDLE_IDENTIFIER *.xcodeproj/project.pbxproj | xargs | cut -d ' ' -f 3 | sed 's~;~~g'`
echo "creating $BUNDLE_IDENTIFIER"

[[ $BUNDLE_IDENTIFIER ]] || die "your current working directory doesn't seem to be an xcode project"


APP_NAME=${BUNDLE_IDENTIFIER##*.}
PACKAGE=${BUNDLE_IDENTIFIER%.*}

# we assume the iOS dir equals the project name
IOS_PROJECT_PATH=$APP_NAME

cp "${TEMPLATE_PATH}/Package.swift" .
cp "${TEMPLATE_PATH}/DemoApp/androidMain.swift" "$IOS_PROJECT_PATH"

cp -R "${TEMPLATE_PATH}/android" .
rm -rf android/build

PACKAGE_WITH_DASHES=${PACKAGE/.//}
rm -rf android/app/src/main/java/
mkdir -p "android/app/src/main/java/${PACKAGE_WITH_DASHES}"

PATH_TO_MAIN_ACTIVITY="${TEMPLATE_PATH}/android/app/src/main/java/com/example/MainActivity.kt"
cp $PATH_TO_MAIN_ACTIVITY "android/app/src/main/java/${PACKAGE_WITH_DASHES}"

FILES_TO_CHANGE=(
    "Package.swift"
    "android/app/build.gradle"
    "android/app/src/main/AndroidManifest.xml"
    "android/app/CMakeLists.txt"
    "android/app/src/main/java/${PACKAGE_WITH_DASHES}/MainActivity.kt"
)

for file in ${FILES_TO_CHANGE[@]}
do
    sed -i '' "s~DemoApp~${APP_NAME}~g" $file
    sed -i '' "s~com.example~${PACKAGE}~g" $file
done

sed -i '' "s~../../~../UIKit~g" android/settings.gradle
sed -i '' "s~../../../~../../UIKit~g" android/app/CMakeLists.txt

PACKAGE_WITH_UNDERSCORES=${PACKAGE/./_}
sed -i '' "s~com_example~${PACKAGE_WITH_UNDERSCORES}~g" ${IOS_PROJECT_PATH}/androidMain.swift

echo "Finished creating ${PACKAGE}.${APP_NAME}"
